blank_issues_enabled: false
contact_links:
  - name: Qiskit Textbook issues
    url: https://github.com/Qiskit/platypus/issues/new/choose
    about: Please open issues related to the Qiskit Textbook here.
